# Generated by Django 5.0.1 on 2026-01-22 09:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Token')),
                ('organization_name', models.CharField(blank=True, max_length=255, verbose_name="Nom de l'organisation")),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Prénom')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Nom')),
                ('is_used', models.BooleanField(default=False, verbose_name='Utilisé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('expires_at', models.DateTimeField(verbose_name="Date d'expiration")),
            ],
            options={
                'verbose_name': 'Token de vérification',
                'verbose_name_plural': 'Tokens de vérification',
                'db_table': 'email_verification_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_unit', models.CharField(choices=[('km', 'Kilomètres'), ('miles', 'Miles')], default='km', max_length=10, verbose_name='Unité de distance')),
                ('fuel_unit', models.CharField(choices=[('liters', 'Litres'), ('gallons', 'Gallons')], default='liters', max_length=10, verbose_name='Unité de carburant')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('ln', 'Lingala')], default='fr', max_length=10, verbose_name='Langue')),
                ('timezone', models.CharField(choices=[('Africa/Kinshasa', 'Kinshasa (WAT)'), ('Africa/Lubumbashi', 'Lubumbashi (CAT)'), ('Europe/Paris', 'Paris (CET)'), ('UTC', 'UTC')], default='Africa/Kinshasa', max_length=50, verbose_name='Fuseau horaire')),
                ('date_format', models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='DD/MM/YYYY', max_length=20, verbose_name='Format de date')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Notifications par email')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='Notifications par SMS')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Notifications push')),
                ('maintenance_alerts', models.BooleanField(default=True, verbose_name='Alertes de maintenance')),
                ('incident_alerts', models.BooleanField(default=True, verbose_name="Alertes d'incidents")),
                ('fuel_alerts', models.BooleanField(default=True, verbose_name='Alertes carburant')),
                ('report_reminders', models.BooleanField(default=True, verbose_name='Rappels de rapports')),
                ('daily_summary', models.BooleanField(default=False, verbose_name='Résumé quotidien')),
                ('weekly_summary', models.BooleanField(default=True, verbose_name='Résumé hebdomadaire')),
                ('theme', models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre'), ('auto', 'Automatique')], default='light', max_length=20, verbose_name='Thème')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Préférences utilisateur',
                'verbose_name_plural': 'Préférences utilisateurs',
                'db_table': 'user_preferences',
            },
        ),
    ]
