# Generated by Django 5.0.1 on 2026-01-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userpreferences_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='primary_color',
            field=models.CharField(default='#6A8A82', max_length=7, verbose_name='Couleur principale'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='secondary_color',
            field=models.CharField(default='#B87333', max_length=7, verbose_name='Couleur secondaire'),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=10, verbose_name='Langue'),
        ),
    ]
