# Generated by Django 5.1.7 on 2026-05-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userpreferences_primary_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Identifiant technique du module (ex: incidents, vehicles).', unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Décocher pour retirer ce module de toute la plateforme.', verbose_name='Disponible globalement')),
                ('order', models.PositiveIntegerField(default=100, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'db_table': 'modules',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='modules',
            field=models.ManyToManyField(blank=True, help_text="Modules auxquels cette organisation a accès. Une organisation peut par exemple n'avoir que le module 'incidents'.", related_name='organizations', to='accounts.module', verbose_name='Modules activés'),
        ),
    ]
