# Generated by Django 5.0.1 on 2026-01-22 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailverificationtoken_userpreferences'),
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name="Motif d'annulation"),
        ),
        migrations.AddField(
            model_name='mission',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'annulation"),
        ),
        migrations.AddField(
            model_name='mission',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_missions', to=settings.AUTH_USER_MODEL, verbose_name='Annule par'),
        ),
        migrations.CreateModel(
            name='TripPause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='Debut de la pause')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin de la pause')),
                ('duration_minutes', models.IntegerField(default=0, verbose_name='Duree (minutes)')),
                ('reason', models.CharField(choices=[('break', 'Pause'), ('meal', 'Repas'), ('fuel', 'Ravitaillement'), ('traffic', 'Trafic'), ('other', 'Autre')], default='break', max_length=20, verbose_name='Raison')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='fleet.trip', verbose_name='Trajet')),
            ],
            options={
                'verbose_name': 'Pause de trajet',
                'verbose_name_plural': 'Pauses de trajet',
                'db_table': 'trip_pauses',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('mission_created', 'Mission créée'), ('mission_started', 'Mission démarrée'), ('mission_completed', 'Mission terminée'), ('mission_cancelled', 'Mission annulée'), ('incident_reported', 'Incident signalé'), ('incident_resolved', 'Incident résolu'), ('vehicle_status_changed', 'Statut véhicule changé'), ('vehicle_created', 'Véhicule ajouté'), ('vehicle_maintenance', 'Maintenance véhicule'), ('driver_status_changed', 'Statut chauffeur changé'), ('driver_created', 'Chauffeur ajouté'), ('trip_started', 'Trajet démarré'), ('trip_paused', 'Trajet en pause'), ('trip_resumed', 'Trajet repris'), ('trip_completed', 'Trajet terminé')], max_length=50, verbose_name="Type d'activité")),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('success', 'Succès'), ('error', 'Erreur')], default='info', max_length=20, verbose_name='Sévérité')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='fleet.driver', verbose_name='Chauffeur')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='fleet.incident', verbose_name='Incident')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='fleet.mission', verbose_name='Mission')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.organization', verbose_name='Organisation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='fleet.vehicle', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Activité',
                'verbose_name_plural': 'Activités',
                'db_table': 'activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='activities_organiz_d88ee6_idx'), models.Index(fields=['activity_type', '-created_at'], name='activities_activit_b6cd50_idx')],
            },
        ),
        migrations.CreateModel(
            name='DriverNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('mission_assigned', 'Mission assignee'), ('mission_updated', 'Mission modifiee'), ('mission_cancelled', 'Mission annulee'), ('mission_started', 'Mission demarree'), ('mission_completed', 'Mission terminee'), ('alert', 'Alerte'), ('reminder', 'Rappel'), ('system', 'Systeme')], max_length=30, verbose_name='Type de notification')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute'), ('urgent', 'Urgente')], default='normal', max_length=20, verbose_name='Priorite')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Donnees supplementaires')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu a')),
                ('push_sent', models.BooleanField(default=False, verbose_name='Push envoye')),
                ('push_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Push envoye a')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Cree par')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='fleet.driver', verbose_name='Conducteur')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='fleet.mission', verbose_name='Mission')),
            ],
            options={
                'verbose_name': 'Notification conducteur',
                'verbose_name_plural': 'Notifications conducteur',
                'db_table': 'driver_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['driver', 'is_read'], name='driver_noti_driver__729f3c_idx'), models.Index(fields=['notification_type', 'created_at'], name='driver_noti_notific_d9b31d_idx')],
            },
        ),
        migrations.CreateModel(
            name='MissionAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('delay_start', 'Retard au demarrage'), ('delay_progress', 'Retard en cours'), ('delay_arrival', "Retard à l'arrivée"), ('route_deviation', 'Deviation de route'), ('long_stop', 'Arret prolonge'), ('speed_violation', 'Exces de vitesse'), ('geofence_exit', 'Sortie de zone')], max_length=30, verbose_name="Type d'alerte")),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('critical', 'Critique')], default='warning', max_length=20, verbose_name='Severite')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('delay_minutes', models.IntegerField(blank=True, null=True, verbose_name='Retard en minutes')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('is_acknowledged', models.BooleanField(default=False, verbose_name='Acquittee')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Acquittee a')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Acquittee par')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='fleet.mission', verbose_name='Mission')),
            ],
            options={
                'verbose_name': 'Alerte mission',
                'verbose_name_plural': 'Alertes mission',
                'db_table': 'mission_alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mission', 'alert_type'], name='mission_ale_mission_068ef6_idx'), models.Index(fields=['is_acknowledged', 'created_at'], name='mission_ale_is_ackn_cd856a_idx')],
            },
        ),
    ]
