# Generated by Django 5.0.1 on 2026-01-22 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_mission_cancellation_reason_mission_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='fleet.driver', verbose_name='Chauffeur'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='fleet.trip', verbose_name='Trajet'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='fleet.vehicle', verbose_name='Véhicule'),
        ),
    ]
