# Generated by Django 5.0.1 on 2026-01-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_incident_optional_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelrecord',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Prix unitaire'),
        ),
    ]
