# Generated by Django 5.0.1 on 2026-01-29 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_alter_fuel_unit_price_max_digits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivernotification',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_driver_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Cree par'),
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('incident_reported', 'Incident signale'), ('incident_updated', 'Incident mis a jour'), ('incident_resolved', 'Incident resolu'), ('maintenance_due', 'Maintenance a prevoir'), ('maintenance_overdue', 'Maintenance en retard'), ('maintenance_completed', 'Maintenance terminee'), ('fuel_low', 'Niveau carburant bas'), ('fuel_anomaly', 'Anomalie carburant'), ('mission_completed', 'Mission terminee'), ('mission_delayed', 'Mission accompli'), ('driver_license_expiring', 'Permis conducteur expire bientot'), ('driver_document_expiring', 'Document conducteur expire bientot'), ('vehicle_insurance_expiring', 'Assurance vehicule expire bientot'), ('vehicle_inspection_due', 'Controle technique a prevoir'), ('alert', 'Alerte'), ('reminder', 'Rappel'), ('system', 'Systeme'), ('report_ready', 'Rapport disponible')], max_length=30, verbose_name='Type de notification')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute'), ('urgent', 'Urgente')], default='normal', max_length=20, verbose_name='Priorite')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Donnees supplementaires')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lu a')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email envoye')),
                ('sms_sent', models.BooleanField(default=False, verbose_name='SMS envoye')),
                ('push_sent', models.BooleanField(default=False, verbose_name='Push envoye')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_notifications', to='fleet.driver', verbose_name='Conducteur')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_notifications', to='fleet.incident', verbose_name='Incident')),
                ('maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_notifications', to='fleet.maintenancerecord', verbose_name='Maintenance')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_notifications', to='fleet.mission', verbose_name='Mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_notifications', to='fleet.vehicle', verbose_name='Vehicule')),
            ],
            options={
                'verbose_name': 'Notification utilisateur',
                'verbose_name_plural': 'Notifications utilisateur',
                'db_table': 'user_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='user_notifi_user_id_ea6762_idx'), models.Index(fields=['notification_type', 'created_at'], name='user_notifi_notific_645560_idx'), models.Index(fields=['user', 'notification_type', 'is_read'], name='user_notifi_user_id_64a763_idx')],
            },
        ),
    ]
