# Generated by Django 5.1.7 on 2026-03-23 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_vehicle_maintenance_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('carte_grise', 'Carte grise'), ('assurance', 'Assurance'), ('visite_technique', 'Visite technique'), ('vignette', 'Vignette')], max_length=30, verbose_name='Type de document')),
                ('document_number', models.CharField(max_length=100, verbose_name='Numéro du document')),
                ('issue_date', models.DateField(verbose_name="Date d'émission")),
                ('expiry_date', models.DateField(verbose_name="Date d'expiration")),
                ('file', models.FileField(blank=True, null=True, upload_to='vehicle_documents/', verbose_name='Fichier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='fleet.vehicle', verbose_name='Véhicule')),
            ],
            options={
                'verbose_name': 'Document véhicule',
                'verbose_name_plural': 'Documents véhicules',
                'db_table': 'vehicle_documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
