# Generated by Django 5.1.7 on 2026-03-25 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_add_vehicle_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Ordre')),
                ('address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longitude')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='fleet.mission', verbose_name='Mission')),
            ],
            options={
                'verbose_name': 'Point de passage',
                'verbose_name_plural': 'Points de passage',
                'db_table': 'mission_checkpoints',
                'ordering': ['order'],
                'unique_together': {('mission', 'order')},
            },
        ),
    ]
