# Generated by Django 5.1.7 on 2026-03-25 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0010_missioncheckpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('delivery', 'Livraison'), ('client', 'Client'), ('mechanical', 'Panne'), ('checkpoint', 'Controle'), ('other', 'Autre')], max_length=20, verbose_name='Raison')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('stopped_at', models.DateTimeField(verbose_name="Heure de l'arret")),
                ('duration_seconds', models.IntegerField(default=0, verbose_name="Duree de l'arret (secondes)")),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='fleet.trip', verbose_name='Trajet')),
            ],
            options={
                'verbose_name': 'Arret de trajet',
                'verbose_name_plural': 'Arrets de trajet',
                'db_table': 'trip_stops',
                'ordering': ['-stopped_at'],
            },
        ),
    ]
