# Generated by Django 5.1.7 on 2026-06-15 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0011_add_trip_stop_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionalert',
            name='alert_type',
            field=models.CharField(choices=[('delay_start', 'Retard au demarrage'), ('delay_progress', 'Retard en cours'), ('delay_arrival', "Retard a l'arrivee"), ('route_deviation', 'Deviation de route'), ('long_stop', 'Arret prolonge'), ('speed_violation', 'Exces de vitesse'), ('geofence_exit', 'Sortie de zone')], max_length=30, verbose_name="Type d'alerte"),
        ),
        migrations.CreateModel(
            name='DriverPushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='ExponentPushToken[...]', max_length=255, unique=True, verbose_name='Jeton Expo')),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web'), ('unknown', 'Inconnu')], default='unknown', max_length=20, verbose_name='Plateforme')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise a jour')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Derniere utilisation')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to='fleet.driver', verbose_name='Conducteur')),
            ],
            options={
                'verbose_name': 'Jeton push conducteur',
                'verbose_name_plural': 'Jetons push conducteur',
                'db_table': 'driver_push_tokens',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['driver', 'is_active'], name='driver_push_driver__0495a5_idx')],
            },
        ),
    ]
