# Generated by Django 5.1.7 on 2026-06-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0012_alter_missionalert_alert_type_driverpushtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivernotification',
            name='notification_type',
            field=models.CharField(choices=[('mission_assigned', 'Mission assignée'), ('mission_updated', 'Mission modifiée'), ('mission_cancelled', 'Mission annulée'), ('mission_started', 'Mission démarrée'), ('mission_completed', 'Mission terminée'), ('alert', 'Alerte'), ('reminder', 'Rappel'), ('system', 'Système')], max_length=30, verbose_name='Type de notification'),
        ),
        migrations.AlterField(
            model_name='drivernotification',
            name='priority',
            field=models.CharField(choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute'), ('urgent', 'Urgente')], default='normal', max_length=20, verbose_name='Priorité'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='priority',
            field=models.CharField(choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute'), ('urgent', 'Urgente')], default='normal', max_length=20, verbose_name='Priorité'),
        ),
    ]
